"""empty message

Revision ID: 0a24d676c940
Revises: 35db1603517d
Create Date: 2020-09-05 00:09:24.223591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a24d676c940"
down_revision = "35db1603517d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bills", sa.Column("is_billed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "is_billed")
    # ### end Alembic commands ###
