"""empty message

Revision ID: 24fa4244490e
Revises: bce6265cd604
Create Date: 2020-12-18 05:42:12.554666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fa4244490e'
down_revision = 'bce6265cd604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_user', sa.Column('ref_code', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ab_user', 'ref_code')
    # ### end Alembic commands ###
