"""empty message

Revision ID: 95c40fb2ae77
Revises: ebbbe58ddf65
Create Date: 2020-10-27 18:50:41.352922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95c40fb2ae77'
down_revision = 'ebbbe58ddf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_policy', sa.Column('operator_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commission_policy', 'operator_type', ['operator_type_id'], ['id'])
    op.drop_column('commission_policy', 'operator_type')
    op.add_column('providers', sa.Column('commission_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'commission_fee')
    op.add_column('commission_policy', sa.Column('operator_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.drop_constraint(None, 'commission_policy', type_='foreignkey')
    op.drop_column('commission_policy', 'operator_type_id')
    # ### end Alembic commands ###
