"""empty message

Revision ID: a98f39f5f57e
Revises: 59dbb9639079
Create Date: 2020-12-18 07:47:07.256967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a98f39f5f57e'
down_revision = '59dbb9639079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_transactions', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('credit_transactions', 'transaction_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('credit_transactions', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_transactions', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('credit_transactions', 'transaction_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('credit_transactions', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
