"""empty message

Revision ID: bce6265cd604
Revises: 7235f2652b45
Create Date: 2020-11-11 12:52:57.424387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce6265cd604'
down_revision = '7235f2652b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('exemption', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'commission_policy', ['operator_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commission_policy', type_='unique')
    op.drop_column('bills', 'exemption')
    # ### end Alembic commands ###
