"""empty message

Revision ID: ebbbe58ddf65
Revises: 1148ec381aee
Create Date: 2020-10-21 23:10:35.279278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbbe58ddf65'
down_revision = '1148ec381aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('ref_addition', sa.Float(), nullable=True))
    op.add_column('bills', sa.Column('ref_multiply', sa.Float(), nullable=True))
    op.add_column('bills', sa.Column('ref_rate', sa.Float(), nullable=True))
    op.add_column('bills', sa.Column('ref_terrif_code', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'ref_terrif_code')
    op.drop_column('bills', 'ref_rate')
    op.drop_column('bills', 'ref_multiply')
    op.drop_column('bills', 'ref_addition')
    # ### end Alembic commands ###
